language: node_js
node_js:
- node
cache: npm
script:
- "./bin/run --version"
- "./bin/run --help"
- npm run test
deploy:
  provider: npm
  email: enderson.pan@gmail.com
  api_key:
    secure: i3DkUXQg50ipWeWvRTJ+FD0d+A0ieJnNasfJZ0xUWLuJ60vs+QeqA2KYVXJJkNIupIuu/cxcXxurh4LzkzkDwlFWHVLUJ1BaqaEuDshUCscZZao7JyqQysfMOOq+o8osgPMxXs5zTPmFDLYgcwFi8/h/o75LqWdZYCJlBvYp5hvIcmlPFA3Oxw/wYYl2ydhvoHqarTCG4Xa5qIDvypSPHlnLLLqjatGI86CdXYXlHXBKz9DCC3JM/XPgwT99ahudnyjNXHqSTrDeDMj74IT3kUI4XdE4CVxz5QoNSk9U2utSDgDfDbJuY3DphjTZwE2XlMNeFIBGdvFHHqH7pIy1Xc7k3jkZhBylV40KB0/jForl85VJ2bTYDDea2/dNYi2nk4C/KqJ6WE6Duu71BgEfbhWs5dT5OnXDnPq1wIBRr76Y/NYLGj0Ro6R4IrQiyQnG6Fx3NBKnXTm3qEDeQTFnV/UYMFYsNdJkcGSGP2iX6aKAxBO8OaWV3gkctQPk8ksuiJdlbN7JHXAp81ZG5Sn9zh0DD+6+hmyU7YGQ4bgf6RMyXOcrX628i07a1xMrogYqOQaBfGHJ5xg5flQ1RGjvAr+Ifl6DlgdZRZ+bom9E3365pncpARML4DWnXgeML7wD7R1kkezxobsizNsbkktB+detWGUiu6P37EkwGCJ0hBE=
  on:
    tags: true
    repo: holytiny/yaml-profile
    branch: main
  skip_cleanup: 'true'
